# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-test:
    uses: alithethird/charm-ci/.github/workflows/integration-test.yml@feat/pre-build-rock-script
    permissions:
      contents: read
      packages: write
      actions: read
    with:
      pre-build-rock-script: ./download_netbox.sh
