name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: 4/edge
      charmcraft-channel: "latest/edge"
      resource-mapping: '{"netbox": "django-app-image"}'
